databases:
  - name: react-crud-furniturestore
    databaseName: react_crud_furniturestore
    user: sonamkaria

services:
  - type: web
    name: react-crud-furniturestore
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: react-crud-furniturestore
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false